name: Rust Cross-Compilation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
            - target: armv7-unknown-linux-gnueabihf
              os: ubuntu-latest
            - target: aarch64-unknown-linux-gnu
              os: ubuntu-latest
            - target: x86_64-unknown-linux-gnu
              os: ubuntu-latest
            - target: x86_64-apple-darwin
              os: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install protobuf-compiler

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Setup cross-compilation for ARM targets (Linux only)
      if: startsWith(matrix.target, 'arm') || startsWith(matrix.target, 'aarch64')
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
        rustup target add ${{ matrix.target }}

    - name: Build for target
      run: cross build --release --target ${{ matrix.target }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target }}-artifact
        path: target/${{ matrix.target }}/release/
